### PR TITLE
Add your own formspree link on form action.

### PR DESCRIPTION
**Pull request by Kingsleymuturi**
I am receiving emails from your account eg. from a guy called tito his email titoman@gmail.com saying hey there...please remove my formspree link from your form action and add yours to receive emails from your site

### CODE REVIEW

**Comment by Kingsleymuturi** [comment]
please do that

**Comment by Motistrings** [comment]
Oww i used that link coz i thought its universal

**Comment by Motistrings** [comment]
lemme do that

**Comment by Kingsleymuturi** [comment]
Yeah please do change the link on form action
*Kingsley.*

**Pull request closed without merging**
